# I use tpm to manage my plugins
# so get that https://github.com/tmux-plugins/tpm
# follow the install instructions, then hit prefix-I

# I also set the backtick (`) as my tmux control/prefix key:
# this may not be what you expect.
unbind C-b
set -g prefix `
# now let me actually type ` as well
bind-key ` send-prefix

#I keep pressing m instead of n...
unbind m
# terminal
set-option -sa terminal-overrides ",xterm*:Tc"
# mouse off
set -g mouse off
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @catppuccin_flavor 'macchiato' # latte,frappe, macchiato or mocha
set -g @catppuccin_left_separator "█"
set -g @catppuccin_right_separator "█"

# Easy bindings for split panes
unbind %
bind | split-window -h
bind - split-window -v

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
