# I use tpm to manage my plugins
# so get that https://github.com/tmux-plugins/tpm
# follow the install instructions, then hit prefix-I

# I also set the backtick (`) as my tmux control/prefix key:
# this may not be what you expect.
unbind C-b
set -g prefix `
# now let me actually type ` as well
bind-key ` send-prefix

#I keep pressing m instead of n...
unbind m
# terminal
set-option -sa terminal-overrides ",xterm*:Tc"
# mouse off
set -g mouse off
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins 'cpu-usage time'
# per default available colors: white, gray, dark_gray, light_purple, 
# dark_purple, cyan, green, orange, red, pink, yellow
set -g @dracula-cpu-usage-colors "green dark_gray"
#set -g @dracula-time-colors "pink dark_gray"
set -g @dracula-time-colors "light_purple dark_gray"
set -g @dracula-day-month true
set -g @dracula-cpu-display-load true
set -g @dracula-cpu-usage-label " "
set -g @dracula-show-flags true
set -g @dracula-show-empty-plugins false
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon "#h "
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# Easy bindings for split panes
unbind %
bind | split-window -h
bind - split-window -v

# Initialize TMUX plugin manager... 
# (keep this line at the very bottom of tmux.conf!)
run '~/.tmux/plugins/tpm/tpm'
